title: "sayoon.shell"
tagline: ""
description: "개발바닥 블로그"
github_username: sayoonnn
url: "https://sayoonnn.github.io"

image_dir: /assets/images

include:
  - _archives

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

highlighter: rouge

header_pages:
  -

theme_config:
  back_home_text: ".."
  date_format: "%m %d %Y" # customize how date is formatted
  show_description: true

markdown: kramdown
kramdown:
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  ps:
    output: true