title: "sayoon.shell"
tagline: ""
description: "개발바닥 블로그"
github_username: sayoonnn
baseurl: "/"
url: "https://sayoonnn.github.io"
asset_url: /asset

include:
  - _archives

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

sass:
  style: compressed

highlighter: rouge

header_pages:
  -

theme_config:
  back_home_text: ".."
  date_format: "%m %d %Y" # customize how date is formatted
  show_description: true

markdown: kramdown
kramdown:
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# set the size of the text to 'large' or 'small', default is small
font-size: large

collections:
  ps:
    output: true

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-1LKH5C0HN4"
    anonymize_ip         : # true, false (default)
