# build Settings
enableRobotsTXT = true
enableGitInfo = true
cleanDestinationDir = true
forceSyncStatic = true


baseurl = "/"
defaultContentLanguage = "ko"
languageCode = "ko-KR"
pagerSize = 5
title = "sayoonnn.dev"
subtitle = "개발바닥"


[params]
	# dir name of your main content (default is `content/posts`).
	# the list of set content will show up on your index page (baseurl).
	contentTypeName = "posts"

	# ["orange", "blue", "red", "green", "pink"]
  # themeColor = "green"

	# if you set this to 0, only submenu trigger will be visible
	showMenuItems = 1

	# show selector to switch language
	showLanguageSelector = false

	# set theme to full screen width
	fullWidthTheme = false

	# center theme with default width
	centerTheme = true

	# if your resource directory contains an image called `cover.(jpg|png|webp)`,
	# then the file will be used as a cover automatically.
	# With this option you don't have to put the `cover` param in a front-matter.
	autoCover = true

	# set post to show the last updated
	# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
	showLastUpdated = true

	#set a custom favicon (default is a `themeColor` square)
	favicon = "favicon/favicon.png"

	# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
	updatedDatePrefix = "마지막 수정"

	# set all headings to their default size (depending on browser settings)
	# oneHeadingSize = true # default

	# whether to show a page's estimated reading time
	# readingTime = false # default

	# whether to show a table of contents
	# can be overridden in a page's front-matter
	# Toc = false # default

	# set title for the table of contents
	# can be overridden in a page's front-matter
	# TocTitle = "Table of Contents" # default


	# you can set a banner on the top of the page with a call to action
	# defaults: dismissible = false; URL is optional
	# [params.banner]
	# dismissible = false
	# text = "Check it out on GitHub"
	# url = "https://github.com/mirus-ua/hugo-theme-re-terminal"



[params.twitter]
	# set Twitter handles for Twitter cards
	# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
	# do not include @
	creator = ""
	site = ""

[languages]
	[languages.ko.params]
		languageName = "Korean"
		title = "sayoonnn"
		subtitle = "개발바닥"
		owner = "sayoonnn"
		keywords = "개발"
		copyright = ""
		menuMore = "링크"
		readMore = " 더보기 "
		readOtherPosts = "다른 글들"
		newerPosts = "새 글"
		olderPosts = "이전 글"
		missingContentMessage = "저런! 페이지를 찾을 수 없군요"
		missingBackButtonLabel = "돌아가기"
		minuteReadingTime = "분"
		words = "단어"

		[languages.ko.params.logo]
			logoText = "sayoonnn.shell"
			logoHomeLink = "/"

		[languages.ko.menu]
			[[languages.ko.menu.main]]
				identifier = "about"
				name = "/about me"
				url = "/about"
		
			[[languages.ko.menu.main]]
				identifier = "github"
				name = "/github"
				url = "https://github.com/sayoonnn"
				params = { NewTab = true }

			[[languages.ko.menu.main]]
				identifier = "blogrepo"
				name = "/blog_repo"
				url = "https://github.com/sayoonnn/sayoonnn.github.io"
				params = { NewTab = true }

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[mediaTypes]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]
